name: Stage

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: stage commits
        run: ./src/release.sh stage src
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
