name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: prepare release.sh
        run: |
          mkdir -p /opt/release.sh/
          /bin/bash -c "$(curl https://raw.githubusercontent.com/634750802/release.sh/HEAD/download.sh)" - /opt/release.sh/
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: release
        run: |
          git config --global user.name "Jagger's Bot"
          git config --global user.email "634750802@qq.com"
          /opt/release.sh/release.sh release src
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
